version: '2'

services:
  jsreport:
    image: jsreport/jsreport
    container_name: jsreport
    hostname: jsreport
    ports:
      - 5488:5488
  consul:
    image: consul
    container_name: consul
    network_mode: host
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: localhost
    network_mode: host
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    network_mode: host
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: "localhost:2181"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  colocate-pipe:
    build: ./pipe
    image: colocate-pipe
    container_name: colocate-pipe
    network_mode: host
  colocate-compute:
    build: ./compute
    image: colocate-compute
    container_name: colocate-compute
    network_mode: host
  colocate-summary:
    build: ./summary
    image: colocate-summary
    container_name: colocate-summary
    network_mode: host
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    network_mode: host
